### ISSUE TITLE
User Story: Administrator Login

### ISSUE THREAD

**Issue by murphyschaff** [UCCS-CS4300-5300/group3-spring2024#2]
Velocity: 1

As a site administrator, I want to be able to login to an Admin specific panel, so that I can have access to privileged data, without non privileged users having the same access.

Happy Path:
A privileged user enters the administration login page.
Correct Admin specific credentials are entered in the username and password field.
User is granted access to the administration panel of the site.

Sad Path:
A normal user attempts to login to the administration login page.
Correct, non administration, credentials are entered into the username and password fields.
User is denied access to the administration panel.

**Comment by neeleshsai23** [comment]
Acceptance Criteria:
1) Can be able to differentiate from a user site.
2) Can be able to block a user.
