### ISSUE TITLE
User Story: Flight Filtering Options

### ISSUE THREAD

**Issue by murphyschaff** [UCCS-CS4300-5300/group3-spring2024#6]
Velocity: 4

As a user, I want to filter the search results by total time, departure/arrival times, price, and airlines, so that I can find the flight that best fits my preferences and budget.

Happy Path:

The user applies filters for departure time, price, and airline.
The system immediately updates the list to only show flights that match the filters.
The user finds a flight that meets their specific requirements and proceeds to booking.

Sad Path:

The user applies filters that result in no flights matching the criteria.
The system displays a message suggesting the user to adjust the filters or try different travel dates.

**Comment by neeleshsai23** [comment]
<img width="1067" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0ZwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5bc59d98fc3bbe6046f40f3526e907fe36f94fff/Flight_Filters_LoFi_1.jpg" alt="Flight_Filters_LoFi_1.jpg" />

**Comment by neeleshsai23** [comment]
Acceptance Criteria:
1) Filtering should be dynamic
2) Page view should be at same position if returned from the booking section
3) Excess details are only shown when the section is expanded.
