### ISSUE TITLE
User Story: User Account Creation and Management

### ISSUE THREAD

**Issue by murphyschaff** [UCCS-CS4300-5300/group3-spring2024#7]
Velocity: 2
As a frequent flier, I want to create a personal account and log in, so that I can save my flight searches, preferences, and receive personalized recommendations.

Happy Path:

The user signs up for an account by providing their email and creating a password.
The system sends a verification email, and the user verifies their account.
The user logs in and can save searches, preferences, and receive recommendations.

Sad Path:

The user attempts to sign up with an email that is already in use.
The system displays an error message informing the user that the email is already associated with an account and suggests logging in or using a different email.

**Comment by neeleshsai23** [comment]
Acceptance Criteria:
1) Login via gmail, microsoft or various mailboxes.
2) Receive notifications or emails about recommendations if subscribed.
3) Easy access to my settings and preferences
