### ISSUE TITLE
User Story: Administrator Statistics

### ISSUE THREAD

**Issue by murphyschaff** [UCCS-CS4300-5300/group3-spring2024#9]
Velocity: 8

As an administrator, I want to be able to track the statistics of each airport and plane so that I can use it to recommend better airports to customers.

Happy Path:
An administrator logs in to an admin account
An administrator looks up a specific airline
An administrator is met with a page of statistics about that airline

Sad Path:
An administrator logs in to an admin account
An administrator looks up a specific airline
The airline is not in the database/ doesn’t have sufficient data

**Comment by neeleshsai23** [comment]
<img width="1155" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1pwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5bde04bb252ee90e659547e3e9f46e4ab4c7270b/Flight_Statistics_LoFi_1.jpg" alt="Flight_Statistics_LoFi_1.jpg" />

**Comment by neeleshsai23** [comment]
Acceptance Criteria:
1) Need good graphical representation of data
2) Detailed description when hovered or clicked
3) Responsiveness
4) Good Visual design
